import { describe, it, expect, vi, beforeEach, beforeAll, afterEach } from "vitest";
import { render, screen, waitFor, within, cleanup } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router";
import axios from "axios";
import { UIProvider } from "@ui/lib/ui-renderer/provider";
import { TooltipProvider } from "@ui/components/tooltip";
import { ViewPage } from "@ui/lib/ui-renderer/view-page";
import type { UIServices } from "@ui/lib/ui-renderer/registry";

// Mock axios
vi.mock("axios");
const mockedAxios = vi.mocked(axios);

// Import mock data (generated by backend rake task)
import ribRequestsSchema from "../mocks/views/rib_check_requests_index.json";
import schemasData from "../mocks/schemas.json";

beforeAll(() => {
  global.ResizeObserver = class ResizeObserver {
    observe() {}
    unobserve() {}
    disconnect() {}
  };
});

const mockTableData = {
  data: [
    {
      id: 1,
      status: "pending",
      request_type: "individual",
      message_body: "Please submit your RIB",
      end_at: "2024-02-15T10:00:00Z",
      created_at: "2024-01-15T10:00:00Z",
    },
    {
      id: 2,
      status: "completed",
      request_type: "common",
      message_body: "RIB collection for payroll",
      end_at: "2024-02-20T10:00:00Z",
      created_at: "2024-01-16T10:00:00Z",
    },
  ],
};

function createMockServices(): UIServices {
  return {
    fetch: vi.fn().mockResolvedValue(mockTableData),
    navigate: vi.fn(),
    toast: vi.fn(),
    confirm: vi.fn().mockResolvedValue(true),
  };
}

function createQueryClient() {
  return new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
}

interface TestWrapperProps {
  children: React.ReactNode;
  services: UIServices;
  locale?: string;
}

function TestWrapper({ children, services, locale = "en" }: TestWrapperProps) {
  const qc = createQueryClient();
  const viewTranslations = ribRequestsSchema.translations?.[locale as keyof typeof ribRequestsSchema.translations] || {};
  const schemaTranslations = schemasData[0]?.translations?.[locale as keyof typeof schemasData[0]["translations"]] || {};

  return (
    <QueryClientProvider client={qc}>
      <MemoryRouter>
        <UIProvider
          services={services}
          translations={{
            views: viewTranslations,
            schemas: schemaTranslations,
            common: {},
          }}
          locale={locale}
        >
          <TooltipProvider>{children}</TooltipProvider>
        </UIProvider>
      </MemoryRouter>
    </QueryClientProvider>
  );
}

describe("RIB Requests Integration", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Default mock: return schema from view endpoint
    mockedAxios.get.mockResolvedValue({ data: ribRequestsSchema });
  });

  afterEach(() => {
    cleanup();
  });

  describe("View Loading via Axios", () => {
    it("fetches view schema from /api/v1/views endpoint", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(mockedAxios.get).toHaveBeenCalledWith(
          "/api/v1/views/workspaces/rib_check_requests/index",
          expect.any(Object)
        );
      });
    });

    it("shows loading state initially", () => {
      mockedAxios.get.mockImplementation(() => new Promise(() => {})); // Never resolves
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      expect(screen.getByText("Loading...")).toBeInTheDocument();
    });
  });

  describe("English Translations", () => {
    it("page title: 'RIB Requests'", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("RIB Requests")).toBeInTheDocument();
      });
    });

    it("page description: 'Manage RIB collection requests'", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("Manage RIB collection requests")).toBeInTheDocument();
      });
    });

    it("new button: 'New Request'", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "New Request" })).toBeInTheDocument();
      });
    });

    it("table headers: Status, Type, Deadline, Created At", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByTestId("table-renderer")).toBeInTheDocument();
      });

      expect(screen.getByText("Status")).toBeInTheDocument();
      expect(screen.getByText("Type")).toBeInTheDocument();
      expect(screen.getByText("Deadline")).toBeInTheDocument();
      expect(screen.getByText("Created At")).toBeInTheDocument();
    });

    it("drawer title: 'New Request'", async () => {
      const user = userEvent.setup();
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "New Request" })).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: "New Request" }));

      await waitFor(() => {
        const drawer = screen.getByTestId("drawer-new_drawer");
        expect(within(drawer).getByText("New Request")).toBeInTheDocument();
      });
    });

    it("view drawer title: 'View Request'", async () => {
      const user = userEvent.setup();
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("Please submit your RIB")).toBeInTheDocument();
      });

      const row = screen.getByText("Please submit your RIB").closest("tr");
      await user.click(row!);

      await waitFor(() => {
        const drawer = screen.getByTestId("drawer-view_drawer");
        expect(within(drawer).getByText("View Request")).toBeInTheDocument();
      });
    });

    it("form field labels in new drawer", async () => {
      const user = userEvent.setup();
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="en">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "New Request" })).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: "New Request" }));

      await waitFor(() => {
        const drawer = screen.getByTestId("drawer-new_drawer");
        // Group labels (not translated)
        expect(within(drawer).getByText("request_details")).toBeInTheDocument();
        expect(within(drawer).getByText("notification_settings")).toBeInTheDocument();
        // Field labels (from view translations: status -> "Status", request_type -> "Type")
        expect(within(drawer).getByLabelText("Status")).toBeInTheDocument();
        expect(within(drawer).getByLabelText("Type")).toBeInTheDocument();
      });
    });
  });

  describe("French Translations", () => {
    it("page title: 'Demandes RIB'", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="fr">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("Demandes RIB")).toBeInTheDocument();
      });
    });

    it("page description: 'Gerer les demandes de collecte RIB'", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="fr">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("Gerer les demandes de collecte RIB")).toBeInTheDocument();
      });
    });

    it("new button: 'Nouvelle Demande'", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="fr">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "Nouvelle Demande" })).toBeInTheDocument();
      });
    });

    it("table headers: Statut, Echeance, Cree le", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="fr">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByTestId("table-renderer")).toBeInTheDocument();
      });

      expect(screen.getByText("Statut")).toBeInTheDocument();
      expect(screen.getByText("Echeance")).toBeInTheDocument();
      expect(screen.getByText("Cree le")).toBeInTheDocument();
    });

    it("form field labels in French", async () => {
      const user = userEvent.setup();
      const services = createMockServices();

      render(
        <TestWrapper services={services} locale="fr">
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "Nouvelle Demande" })).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: "Nouvelle Demande" }));

      await waitFor(() => {
        const drawer = screen.getByTestId("drawer-new_drawer");
        // Field labels from view translations: status -> "Statut", request_type -> "Type"
        expect(within(drawer).getByLabelText("Statut")).toBeInTheDocument();
        expect(within(drawer).getByLabelText("Type")).toBeInTheDocument();
      });
    });
  });

  describe("Table Data", () => {
    it("fetches and displays data", async () => {
      const services = createMockServices();

      render(
        <TestWrapper services={services}>
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("Please submit your RIB")).toBeInTheDocument();
        expect(screen.getByText("RIB collection for payroll")).toBeInTheDocument();
      });

      expect(services.fetch).toHaveBeenCalled();
    });
  });

  describe("New Request Drawer", () => {
    it("clicking 'New Request' opens drawer with form", async () => {
      const user = userEvent.setup();
      const services = createMockServices();

      render(
        <TestWrapper services={services}>
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "New Request" })).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: "New Request" }));

      await waitFor(() => {
        const drawer = screen.getByTestId("drawer-new_drawer");
        expect(within(drawer).getByRole("button", { name: /save/i })).toBeInTheDocument();
      });
    });
  });

  describe("View Drawer", () => {
    it("clicking table row opens view drawer", async () => {
      const user = userEvent.setup();
      const services = createMockServices();

      render(
        <TestWrapper services={services}>
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText("Please submit your RIB")).toBeInTheDocument();
      });

      const row = screen.getByText("Please submit your RIB").closest("tr");
      await user.click(row!);

      await waitFor(() => {
        expect(screen.getByTestId("drawer-view_drawer")).toBeInTheDocument();
      });
    });
  });

  describe("Form Submission", () => {
    it("submitting form calls API and shows toast", async () => {
      const user = userEvent.setup();
      const services = createMockServices();
      services.fetch = vi.fn()
        .mockResolvedValueOnce(mockTableData)
        .mockResolvedValueOnce({ data: { id: 3 } })
        .mockResolvedValueOnce(mockTableData);

      render(
        <TestWrapper services={services}>
          <ViewPage namespace="workspaces" feature="rib_check_requests" view="index" />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByRole("button", { name: "New Request" })).toBeInTheDocument();
      });

      await user.click(screen.getByRole("button", { name: "New Request" }));

      await waitFor(() => {
        expect(screen.getByTestId("drawer-new_drawer")).toBeInTheDocument();
      });

      const drawer = screen.getByTestId("drawer-new_drawer");
      await user.click(within(drawer).getByRole("button", { name: /save/i }));

      await waitFor(() => {
        expect(services.toast).toHaveBeenCalled();
      });
    });
  });
});
