# frozen_string_literal: true

require "rails_helper"
require "rake"

RSpec.describe "core:export_mocks" do
  before(:all) do
    Rails.application.load_tasks
  end

  before(:each) do
    Core::Schema::Registry.clear!
    Core::Features::Registry.clear!
    Rake::Task["core:export_mocks"].reenable
  end

  let(:contact_schema) do
    Class.new(Core::Schema::Base) do
      def self.name
        "ContactsService::ContactSchema"
      end
      title "Contact"
      string :name

      relationships do
        has_many :addresses, schema: :address
      end

      translations(en: { name: "Name" })
    end
  end

  before do
    Core::Schema::Registry.register(contact_schema)

    # Create pack directory structure
    FileUtils.mkdir_p(Rails.root.join("packs/contacts_service/app/frontend"))
  end

  it "exports schemas to pack's frontend test directory" do
    Rake::Task["core:export_mocks"].invoke

    output_file = Rails.root.join(
      "packs/contacts_service/app/frontend/__tests__/mocks/schemas.json"
    )
    expect(File.exist?(output_file)).to be true

    data = JSON.parse(File.read(output_file))
    expect(data.first["slug"]).to eq("contact")
  end

  it "exports all packs automatically" do
    expect { Rake::Task["core:export_mocks"].invoke }
      .to output(/contacts_service: Exported/).to_stdout
  end

  after(:each) do
    # Only clean up mocks generated by the rake task, not other test files
    FileUtils.rm_rf(Rails.root.join("packs/contacts_service/app/frontend/__tests__/mocks/schemas.json"))
    FileUtils.rm_rf(Rails.root.join("packs/contacts_service/app/frontend/__tests__/mocks/relationships.json"))
    FileUtils.rm_rf(Rails.root.join("packs/contacts_service/app/frontend/__tests__/mocks/features.json"))
  end
end
