// Typelizer digest fc48121157e511df1f0c4029c066c4e1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type CoreSerializersItem = {
  id: unknown;
  data: unknown;
  workspace_id: unknown;
  created_by_id: unknown;
  updated_by_id: unknown;
  schema_slug: unknown;
  tool_slug: unknown;
  created_at: unknown;
  updated_at: unknown;
  deleted_at: unknown;
  relationships: unknown;
}

export default CoreSerializersItem;
