// Typelizer digest 587dd555ffd9f5b6f961421a48607223
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type CoreSerializersItem = {
  id: unknown;
  workspace_id: unknown;
  created_by_id: unknown;
  updated_by_id: unknown;
  schema_slug: unknown;
  tool_slug: unknown;
  data: unknown;
  created_at: unknown;
  updated_at: unknown;
  deleted_at: unknown;
}

export default CoreSerializersItem;
