// Typelizer digest e1c17acfc8157c0d27d4321fde3056cb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type UserData = {
  id: number;
  login: string;
  name: string | null;
  email: string | null;
  avatar_url: string | null;
  internal: boolean;
}

type User = {
  user: UserData;
}

export default User;
